nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.17.1.cjs

# Disable build scripts except for the packages listed in package.json dependenciesMeta
enableScripts: false

npmMinimalAgeGate: 7d

plugins:
  # See plugin page for latest version: https://github.com/microsoft/beachball/tree/main/yarn-plugins/engines
  # (Please revert yarn's automatic formatting changes to this file if updating the plugin...)
  - checksum: 96d5dc207a73ce039dc2e902a692ada57e92dfe3a05e5201cd975467c5e307d50c86c7c5480a69e85e01531d37608b327f8f5841b922a610f160ca57f8d756dc
    path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/microsoft/beachball/engines_v0.2.1/yarn-plugins/engines/dist/plugin.js"

engines:
  ignorePackages:
    # These and all related packages are incompatible with 16, but pinned to versions compatible
    # with 18 as a compromise (they had been accidentally updated to versions requiring 18
    # some time ago, and it's only an issue for scenarios using Azure blob storage caching)
    - "@azure/core-auth"
    - "@azure/identity"
    - "@azure/storage-blob"
    # In the production dependency tree of lage, tar is only referenced by the optional dependency
    # fsevents (for macOS only) -> node-gyp:latest -> tar. fsevents is externalized, and node-gyp
    # would need to be manually pinned for older Node versions anyway, so it's not a problem.
    # (fsevents is listed in optionalDependencies of chokidar, which is bundled, so it has to be
    # repeated in lage optionalDependencies to be installed at runtime on relevant systems.)
    - tar
