nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs

# Disable build scripts except for the packages listed in package.json dependenciesMeta
enableScripts: false

# Ban pulling in packages newer than 3 days, except those specifically listed
npmMinimalAgeGate: 3d
npmPreapprovedPackages: ["beachball"]

plugins:
  # See plugin page for latest version: https://github.com/ecraig12345/yarn-plugins/tree/main/plugins/engines
  # (Please revert yarn's automatic formatting changes to this file if updating the plugin...)
  - checksum: d19a26e2cd1ce11ecaf6b3a91b6d07b0e613acd15aa9b4528eb80234153ae0987c5ce13c1019dea3a0df3beba978766865bbe63122d42d36ed201ad1691b7714
    path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/ecraig12345/yarn-plugins/engines_v0.1.4/plugins/engines/dist/plugin.js"

engines:
  ignorePackages:
    # These and all related packages are incompatible with 16, but pinned to versions compatible
    # with 18 as a compromise (they had been accidentally updated to versions requiring 18
    # some time ago, and it's only an issue for scenarios using Azure blob storage caching)
    - "@azure/core-auth"
    - "@azure/identity"
    - "@azure/storage-blob"
    # In the production dependency tree of lage, tar is only referenced by the optional dependency
    # fsevents (for macOS only) -> node-gyp:latest -> tar. fsevents is externalized, and node-gyp
    # would need to be manually pinned for older Node versions anyway, so it's not a problem.
    # (fsevents is listed in optionalDependencies of chokidar, which is bundled, so it has to be
    # repeated in lage optionalDependencies to be installed at runtime on relevant systems.)
    - tar
