nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.17.1.cjs

# Disable build scripts except for the packages listed in package.json dependenciesMeta
enableScripts: false

npmMinimalAgeGate: 7d

plugins:
  # See plugin page for latest version: https://github.com/microsoft/beachball/tree/main/yarn-plugins/engines
  # (PLEASE REVERT yarn's automatic formatting changes to this file if updating the plugin...)
  - checksum: 6516c92d515bf459b635cbd2528af986eb41f174d0ff971409792932af093c18568d8cc4b3e319481820ac3f1b915c177ee1e30a46e933a12e0621145225d075
    path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/microsoft/beachball/yarn-plugin-engines_v0.3.0/yarn-plugins/engines/dist/plugin.js"

engines:
  ignorePackages:
    # These and all related packages are incompatible with 16, but pinned to versions compatible
    # with 18 as a compromise (they had been accidentally updated to versions requiring 18
    # some time ago, and it's only an issue for scenarios using Azure blob storage caching)
    - "@azure/core-auth"
    - "@azure/identity"
    - "@azure/storage-blob"
    # In the production dependency tree of lage, tar is only referenced by the optional dependency
    # fsevents (for macOS only) -> node-gyp:latest -> tar. fsevents is externalized, and node-gyp
    # would need to be manually pinned for older Node versions anyway, so it's not a problem.
    # (fsevents is listed in optionalDependencies of chokidar, which is bundled, so it has to be
    # repeated in lage optionalDependencies to be installed at runtime on relevant systems.)
    - tar
