import * as os from "os";
import * as fs from "fs";
import * as path from "path";
import execa from "execa";

const tmpdir = os.tmpdir();

interface MonorepoPackages {
  [name: string]: {
    internalDeps?: string[];
    scripts?: { [script: string]: string };
    /** Mapping from **package-relative** path to file contents */
    extraFiles?: { [file: string]: string };
  };
}

export interface MonorepoInitParams {
  /** Absolute path to a test fixture to copy (ignored by e2e) */
  fixturePath?: string;
  packages?: MonorepoPackages;
  /** Mapping from repo-relative path to file contents */
  extraFiles?: Record<string, string>;
  /** If true, skip linking packages */
  skipLink?: boolean;
}

export class Monorepo {
  public readonly root: string;

  /** path to `<root>/node_modules` */
  protected readonly nodeModulesPath: string;

  constructor(protected name: string) {
    this.root = fs.mkdtempSync(path.join(tmpdir, `lage-monorepo-${name}-`));
    this.nodeModulesPath = path.join(this.root, "node_modules");
  }

  /**
   * Init the git repo, generate the base files and any specified files, and link packages.
   */
  public async init(params: MonorepoInitParams = {}): Promise<void> {
    await this.gitInit();
    const cwd = this.root;

    const { fixturePath, packages, extraFiles } = params;

    if (fixturePath) {
      fs.mkdirSync(this.root, { recursive: true });
      fs.cpSync(fixturePath, this.root, { recursive: true });
    } else {
      this.generateRepoFiles();
    }

    packages && this.addPackages(packages);
    extraFiles && this.writeFiles(extraFiles);

    !params.skipLink && this.linkPackages();

    // Commit all at the end for efficiency
    execa.sync("git", ["add", "."], { cwd });
    execa.sync("git", ["commit", "-m", "test"], { cwd });
  }

  protected async gitInit(): Promise<void> {
    const cwd = this.root;
    await execa("git", ["init"], { cwd });

    const gitConfigPath = path.join(this.root, ".git", "config");
    let gitConfig = fs.existsSync(gitConfigPath) ? fs.readFileSync(gitConfigPath, "utf-8") : "";
    gitConfig += [
      // Manually add git config instead of running git commands since it's much faster
      "",
      "[user]",
      "    name = test user",
      "    email = you@example.com",
      "[commit]",
      "    gpgsign = false",
    ].join("\n");
    fs.writeFileSync(gitConfigPath, gitConfig, "utf-8");
  }

  /**
   * Simulates a "yarn" call by linking internal packages and generates a yarn.lock file
   */
  private linkPackages(): void {
    const packagesPath = path.join(this.root, "packages");
    const pkgs = fs.readdirSync(packagesPath);

    fs.mkdirSync(this.nodeModulesPath, { recursive: true });

    let yarnYaml = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n`;

    for (const pkg of pkgs) {
      const packagePath = path.join(packagesPath, pkg);
      fs.symlinkSync(packagePath, path.join(this.nodeModulesPath, pkg), "junction");

      const pkgJson = JSON.parse(fs.readFileSync(path.join(packagePath, "package.json"), "utf-8"));
      const deps = pkgJson.dependencies;

      yarnYaml += `"${pkg}@^${pkgJson.version}":\n  version "${pkgJson.version}"\n`;

      if (deps) {
        yarnYaml += `  dependencies:`;
        for (const dep of Object.keys(deps)) {
          yarnYaml += `    "${dep}" "0.1.0"`;
        }
      }
    }

    this.writeFiles({ "yarn.lock": yarnYaml });
  }

  private generateRepoFiles(): void {
    this.writeFiles({
      "package.json": {
        name: this.name,
        version: "0.1.0",
        private: true,
        workspaces: ["packages/*"],
        scripts: {
          bundle: "echo bundle",
          build: "echo build",
          test: "echo test",
          lint: "echo lint",
        },
      },
      "lage.config.js": `module.exports = {
        pipeline: {
          build: ['^build'],
          test: ['build'],
          lint: []
        }
      };`,
      ".gitignore": "node_modules",
    });
  }

  /** Write package files but don't commit. */
  protected addPackages(packages: MonorepoPackages): void {
    const files: Record<string, string | object> = {};

    for (const [name, { internalDeps, scripts, extraFiles }] of Object.entries(packages)) {
      files[`packages/${name}/build.js`] = `console.log('building ${name}');`;
      files[`packages/${name}/test.js`] = `console.log('testing ${name}');`;
      files[`packages/${name}/lint.js`] = `console.log('linting ${name}');`;
      files[`packages/${name}/package.json`] = {
        name,
        version: "0.1.0",
        scripts: scripts || {
          build: "node ./build.js",
          test: "node ./test.js",
          lint: "node ./lint.js",
        },
        dependencies: internalDeps ? Object.fromEntries(internalDeps.map((dep) => [dep, "*"])) : {},
      };
      if (extraFiles) {
        for (const [file, content] of Object.entries(extraFiles)) {
          files[`packages/${name}/${file}`] = content;
        }
      }
    }

    this.writeFiles(files);
  }

  public clone(origin: string): execa.ExecaChildProcess<string> {
    return execa("git", ["clone", origin], { cwd: this.root });
  }

  public push(origin: string, branch: string): execa.ExecaChildProcess<string> {
    return execa("git", ["push", origin, branch], { cwd: this.root });
  }

  public writeFiles(files: { [file: string]: string | object }, options: { executable?: boolean } = {}): void {
    for (const [file, contents] of Object.entries(files)) {
      const out = typeof contents === "string" ? contents : JSON.stringify(contents, null, 2);

      const fullPath = path.isAbsolute(file) ? file : path.join(this.root, file);

      if (!fs.existsSync(path.dirname(fullPath))) {
        fs.mkdirSync(path.dirname(fullPath), { recursive: true });
      }

      fs.writeFileSync(fullPath, out);

      if (options.executable) {
        fs.chmodSync(path.join(this.root, file), 0o755);
      }
    }
  }

  public readFiles(files: string[]): Record<string, string> {
    const contents: Record<string, string> = {};
    for (const file of files) {
      const fullPath = path.isAbsolute(file) ? file : path.join(this.root, file);
      if (!fs.existsSync(fullPath)) {
        throw new Error(`File ${fullPath} does not exist`);
      }
      contents[file] = fs.readFileSync(fullPath, "utf-8");
    }

    return contents;
  }

  public async commitFiles(files: { [name: string]: string | object }, options: { executable?: boolean } = {}): Promise<void> {
    this.writeFiles(files, options);
    await execa("git", ["add", "--", ...Object.keys(files)], { cwd: this.root });
    await execa("git", ["commit", "-m", "commit files"], { cwd: this.root });
  }

  public run(command: string, args?: string[], silent?: boolean, options?: Partial<execa.Options>): execa.ExecaChildProcess<string> {
    return execa("yarn", [...(silent ? ["--silent"] : []), command, ...(args || [])], {
      cwd: this.root,
      shell: true,
      ...options,
    });
  }

  /**
   * Clean up the monorepo. Will retry twice on failure, then warn and continue
   * (since it's a temp directory that will be cleaned up eventually).
   */
  public async cleanup(): Promise<void> {
    const maxRetries = 3;
    let attempts = 0;

    while (attempts < maxRetries) {
      try {
        fs.rmSync(this.root, { recursive: true, force: true });
        break;
      } catch (error) {
        attempts++;
        if (attempts >= maxRetries) {
          // eslint-disable-next-line no-console
          console.warn(`Failed to clean up monorepo at ${this.root} after ${attempts} attempts:`, error);
        } else {
          await new Promise((resolve) => setTimeout(resolve, 500));
        }
      }
    }
  }
}
