name: Docs - PR

# This doesn't actually deploy, just builds the docs folder when it's modified.

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/docusaurus-pr.yml
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test-build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: .nvmrc

      - run: yarn --immutable
        working-directory: docs

      - name: Build website
        working-directory: docs
        run: yarn build
