name: Windows Rolling

on:
  schedule:
    - cron: "30 5,17 * * *"

jobs:
  build:
    strategy:
      matrix:
        node-version: [16.x]
        os: [windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn

      - name: Build, Test (Windows)
        run: yarn lage build test --concurrency 2 --verbose
        env:
          BACKFILL_CACHE_PROVIDER: ${{ secrets.backfill_cache_provider }}
          BACKFILL_CACHE_PROVIDER_OPTIONS: ${{ secrets.backfill_cache_provider_options }}
